// MRS — Gemini prompts log (auto-generated from filenames)
// Edit prompt strings here to refine wording. Image order is chronological.

export const PROMPTS = [
  "Ancient banyan tree",
  "Fern cluster",
  "Alocasia",
  "Cecropia",
  "Nurse log",
  "Bracket fungus",
  "Buriti palm",
  "Inaja palm",
  "Walking palm",
  "Cannonball tree",
  "Munguba tree",
  "Travelers palm",
  "Guarana",
  "Sensitive plant",
  "Aninga",
  "Parrots beak heliconia",
  "Wild papaya",
  "Monkey brush vine",
  "Ginger rhizome",
  "Naked mole rat",
  "Fly agaric",
  "Trapdoor spider",
  "Cordyceps",
  "Underground river eel",
  "Orchid mycorrhizal root",
  "Earthworm cluster",
  "Cave cricket",
  "Pill bug",
  "Army ant bridge",
  "Fossilized earth chunk",
  "Glowing crystal cluster",
  "Gold vein rock",
  "Earth chunk with taproot",
  "Quartz root breaker",
  "Crystalline fungal shelf",
  "Luminous puddle rock",
  "Muddy root ball",
  "Subterranean puddle clump",
  "Earthworm soil clump",
  "Fossil bed debris",
];
